### PR TITLE
Make sure numpy northing array is not modified in place in `to_latlon`

### PR DESCRIPTION
**Pull request by heathhenley**
We were using these eastings / northings (in `np.array`s) after calling the `to_latlon` function and noticed that the northing was being modified. I'm not sure if this is actually intended to be supported in UTM, but I don't think it should be modified as an arg.  It seems like the `-=` operator here was optimized to modify the northings in place, which was a problem for us. Given that the easting is not modified in place, I think it make sense to do it this way instead.

### CODE REVIEW

**Comment by heathhenley** [comment]
Hey @Turbo87 - sorry for the ping, I was just looking through old open stuff I'm on and this came up. Do you think it's suitable to merge or better to close?

**Comment by bartvanandel** [comment]
Maybe to prevent this from being "optimized" into `-=` in the future (as it isn't necessarily trivial why it should be avoided), maybe go for this?

```python
y = northing if northern else northing - 10000000
```

**Comment by heathhenley** [comment]
That works too, maybe adding a comment if you think it's likely to get refactored again?

**Comment by heathhenley** [comment]
Happy add and rebase - this is pretty old so probably behind

**Comment by bartvanandel** [comment]
It's still a clean merge, so it's not that outdated. Checks may fail (unrelated to this PR) due to https://github.com/Turbo87/utm/pull/103 though.

**Comment by heathhenley** [comment]
Ok it's inlined now, I didn't pull down and test though, lmk if you think it's needed.

**Review by bartvanandel — APPROVED** [review]

**Comment by bartvanandel** [comment]
I can't merge, but @Turbo87 can?

**Pull request merged**
