### PR TITLE
Made it posible to choose utm band when converting from lat lon to utm

### LINKED ISSUE #7: lat/lon to forced UTM projection
It would be nice to be able to force a from_latlon convertion into a specific UTM zone.
You see, most of Denmark is positioned in zone 32, while the eastern most part of Sealand (including Copenhagen) and the island Bornholm is located in zone 33. But for simplicity, maps of Denmark are often created, so the entire Sealand is projected in zone 32 and only Bornholm is sometimes projected in zone 33.

Therefore I suggest to add optionally arguments to from_latlon, so one could force it to be converted to a specific UTM zone. 
Example:

~~~~python
def from_latlon(latitude, longitude,force_utm_zome=False,force_utm_letter=None):
..

    if force_utm_zone and force_utm_letter:
        zone_number = int(force_utm_zone)
        zone_letter = force_zone_letter
    else:
        zone_number = latlon_to_zone_number(latitude, longitude)
        zone_letter = latitudeto_zone_letter(latitude)
~~~~

I know it is going to add complexity to your otherwise simple and clean solution, but for some it is required to be able to force UTM zones.

What do you think about the issue?

### PR DESCRIPTION
**Pull request by tibnor**
fixes #7

### CODE REVIEW

**Comment by Turbo87** [comment]
@tibnor sorry for the long wait, could you change your commit to not update the version number of the library please? and I would prefer the parameter to be named `force_zone_number` as suggested in #7.

**Comment by tibnor** [comment]
@Turbo87 The new commits contains your wishes! :-)

**Comment by Turbo87** [comment]
awesome, thank you!

**Comment by Turbo87** [comment]
@tibnor it would be great if you could extend the unit test suite with a test for that new parameter too

**Comment by Turbo87** [comment]
@tibnor I just release v0.4.0 on PyPI including your changes

**Pull request merged**
